//! The `#[typesec_tool(...)]` attribute macro: one declaration, every layer.
//!
//! Annotating a tool function generates a `<fn>_binding()` constructor for
//! the wire-guard [`ToolBinding`], so the function and its security manifest
//! cannot drift apart:
//!
//! ```rust,ignore
//! #[typesec_tool(action = "read", resource = "reports/q1")]
//! fn read_report(args: &serde_json::Value) -> String { ... }
//!
//! let guard = ToolCallGuard::new(engine).bind(read_report_binding());
//! ```
//!
//! Accepted keys: `name` (defaults to the function name), `action`
//! (required), `resource` (required), `resource_arg`, and
//! `required_args = "a, b"`.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::parse::Parser as _;
use syn::punctuated::Punctuated;
use syn::{Error, Expr, ExprLit, ItemFn, Lit, Meta, Token};

struct ToolArgs {
    name: Option<String>,
    action: Option<String>,
    resource: Option<String>,
    resource_arg: Option<String>,
    required_args: Vec<String>,
}

fn lit_str(meta: &Meta) -> syn::Result<String> {
    if let Meta::NameValue(nv) = meta
        && let Expr::Lit(ExprLit {
            lit: Lit::Str(s), ..
        }) = &nv.value
    {
        return Ok(s.value());
    }
    Err(Error::new_spanned(meta, "expected `key = \"value\"`"))
}

fn parse_args(metas: Punctuated<Meta, Token![,]>) -> syn::Result<ToolArgs> {
    let mut args = ToolArgs {
        name: None,
        action: None,
        resource: None,
        resource_arg: None,
        required_args: Vec::new(),
    };
    for meta in &metas {
        let key = meta
            .path()
            .get_ident()
            .map(ToString::to_string)
            .unwrap_or_default();
        match key.as_str() {
            "name" => args.name = Some(lit_str(meta)?),
            "action" => args.action = Some(lit_str(meta)?),
            "resource" => args.resource = Some(lit_str(meta)?),
            "resource_arg" => args.resource_arg = Some(lit_str(meta)?),
            "required_args" => {
                args.required_args = lit_str(meta)?
                    .split(',')
                    .map(str::trim)
                    .filter(|arg| !arg.is_empty())
                    .map(str::to_owned)
                    .collect();
            }
            other => {
                return Err(Error::new_spanned(
                    meta,
                    format!(
                        "unknown typesec_tool key '{other}' (expected name, action, \
                         resource, resource_arg, or required_args)"
                    ),
                ));
            }
        }
    }
    Ok(args)
}

pub(crate) fn typesec_tool_impl(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let function = syn::parse2::<ItemFn>(item)?;
    let metas = Punctuated::<Meta, Token![,]>::parse_terminated.parse2(attr)?;
    let args = parse_args(metas)?;

    let fn_name = function.sig.ident.to_string();
    let tool_name = args.name.unwrap_or_else(|| fn_name.clone());
    let action = args.action.ok_or_else(|| {
        Error::new_spanned(
            &function.sig.ident,
            "typesec_tool requires `action = \"...\"`",
        )
    })?;
    let resource = args.resource.ok_or_else(|| {
        Error::new_spanned(
            &function.sig.ident,
            "typesec_tool requires `resource = \"...\"`",
        )
    })?;

    let binding_fn = format_ident!("{}_binding", function.sig.ident);
    let vis = &function.vis;
    let resource_arg = match &args.resource_arg {
        Some(arg) => quote! { .resource_from_arg(#arg) },
        None => quote! {},
    };
    let required = if args.required_args.is_empty() {
        quote! {}
    } else {
        let items = &args.required_args;
        quote! { .require_args([#(#items),*]) }
    };
    let doc =
        format!("Typesec binding for the `{tool_name}` tool (generated by `#[typesec_tool]`).");

    Ok(quote! {
        #function

        #[doc = #doc]
        #vis fn #binding_fn() -> ::typesec_agent::interop::ToolBinding {
            ::typesec_agent::interop::ToolBinding::new(#tool_name, #action, #resource)
                #resource_arg
                #required
        }
    })
}
